server:
  port: 8080
  debug: true
  read_timeout_seconds: 360
  write_timeout_seconds: 360

database:
  request_timeout_sec: 5
  database: crawler
  collection: peers

resolver:
  request_timeout_sec: 3