# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crawler.fullname" . }}
  labels:
    {{- include "crawler.labels" . | nindent 4 }}
data:
  MONGODB_URI: {{ .Values.secret.mongoURI | b64enc }}
  RESOLVER_API_KEY: {{ .Values.secret.resolverAPIKey | b64enc }}